import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys

WebUI.openBrowser('')

WebUI.navigateToUrl('https://sucourse.sabanciuniv.edu/plus/')

WebUI.click(findTestObject('ReplyDiscussion/Page_SUCourse/a_Login'))

WebUI.click(findTestObject('ReplyDiscussion/Page_SUCourse Authentication choice/a_SUNet users (Sabanc University members)'))

WebUI.setText(findTestObject('ReplyDiscussion/Page_Login - CAS  Central Authentication Service/input_U_username'), 'mohamedkassem')

WebUI.setEncryptedText(findTestObject('ReplyDiscussion/Page_Login - CAS  Central Authentication Service/input_P_password'), 
    'lsh4UT/KYs157Zjg3xgr3w==')

WebUI.click(findTestObject('ReplyDiscussion/Page_Login - CAS  Central Authentication Service/input_Remember Me_submit'))

WebUI.getUrl()

WebUI.click(findTestObject('ReplyDiscussion/Page_Dashboard/a_CS439-202002'))

WebUI.verifyTextPresent('CS439', false)

WebUI.click(findTestObject('ReplyDiscussion/Page_Course CS439-202002/a_Forums'))

WebUI.click(findTestObject('ReplyDiscussion/Page_CS439-202002 Forums/a_Discussion Board'))

WebUI.verifyTextPresent('Discussion Board', false)

WebUI.click(findTestObject('ReplyDiscussion/Page_Discussion Board/a_Looking for 2 More Team Members'))

WebUI.scrollToPosition(0, 500)

WebUI.click(findTestObject('ReplyDiscussion/Page_CS439-202002 Looking for 2 More Team Members/a_Reply'))

WebUI.setText(findTestObject('ReplyDiscussion/Page_CS439-202002 Looking for 2 More Team Members Looking for 2 More Team Members/div_Message_id_messageeditable'), 
    'Hey, this message is generated by an automated test')

WebUI.scrollToPosition(500, 1500)

WebUI.click(findTestObject('ReplyDiscussion/Page_CS439-202002 Looking for 2 More Team Members Looking for 2 More Team Members/input__submitbutton'))

